"""
Agent0: Self-Evolving Research Agent System
Based on "Agent0: Unleashing Self-Evolving Agents from Zero Data via Tool-Integrated Reasoning"

This module implements a self-evolving research system inspired by Agent0's co-evolutionary framework.
The system features curriculum and executor agents that improve through symbiotic competition.
"""

import asyncio
import json
from typing import Dict, List, Any, Optional, Tuple
from datetime import datetime
from pathlib import Path
import numpy as np
from dataclasses import dataclass, field

from agno.agent import Agent
from agno.models.openai import OpenAIChat
from agno.team.team import Team
from agno.db.sqlite import SqliteDb

from tools.parallel_ddg import ParallelDuckDuckGoSearch
from storage.vector_store import VectorStore
from storage.file_manager import FileManager
from utils.logger import get_logger
from refinement.refiner import RefinementEngine
from refinement.evaluator import ResearchEvaluator


logger = get_logger()


@dataclass
class ResearchTask:
    """Represents a research task generated by the curriculum agent."""
    task_id: str
    query: str
    complexity: float  # 0.0 to 1.0
    difficulty: str  # 'easy', 'medium', 'hard', 'frontier'
    tool_requirements: List[str]
    generated_at: datetime
    uncertainty_score: Optional[float] = None
    executor_responses: List[Dict] = field(default_factory=list)
    success_rate: Optional[float] = None


@dataclass
class ExecutorResponse:
    """Represents an executor agent's response to a task."""
    task_id: str
    response: str
    sources: List[Dict]
    tool_calls: List[str]
    confidence: float
    success: bool
    reasoning_steps: List[str]
    execution_time: float


class CurriculumAgent:
    """
    Generates increasingly complex research tasks based on executor performance.
    Implements the curriculum evolution component of Agent0.
    """

    def __init__(self, session_db: SqliteDb, config: Dict[str, Any]):
        """Initialize the curriculum agent."""
        self.session_db = session_db
        self.config = config
        self.iteration = 0
        self.task_history: List[ResearchTask] = []

        # Initialize Agno agent for curriculum generation
        self.agent = Agent(
            model=OpenAIChat(
                id=config.get('model', 'gpt-4'),
                api_key=config.get('api_key')
            ),
            session=session_db,
            description="Curriculum Agent - Generates research tasks",
            instructions=self._get_curriculum_instructions(),
            tools=[ParallelDuckDuckGoSearch()]
        )

        logger.info("CurriculumAgent initialized")

    def _get_curriculum_instructions(self) -> str:
        """Get the system instructions for the curriculum agent."""
        return """
        You are a Curriculum Agent responsible for generating research tasks.

        Your objectives:
        1. Generate research tasks that challenge the current executor capabilities
        2. Increase complexity progressively based on executor performance
        3. Ensure tasks require tool usage (web search, data analysis)
        4. Create diverse tasks across different domains
        5. Target the executor's uncertainty zone (tasks that are neither too easy nor too hard)

        Task Generation Guidelines:
        - Start with basic information retrieval
        - Progress to multi-step reasoning
        - Advance to synthesis and analysis
        - Ultimate goal: Complex, multi-source research with critical evaluation

        Track executor performance and adapt task difficulty accordingly.
        """

    def generate_task(self, executor_performance: Optional[Dict] = None) -> ResearchTask:
        """
        Generate a new research task based on executor performance.

        Args:
            executor_performance: Performance metrics from executor agent

        Returns:
            ResearchTask object
        """
        self.iteration += 1

        # Calculate target difficulty based on performance
        target_difficulty = self._calculate_target_difficulty(executor_performance)

        # Generate task prompt
        prompt = self._create_task_generation_prompt(target_difficulty, executor_performance)

        # Use agent to generate task
        response = self.agent.run(prompt)

        # Parse response into ResearchTask
        task = self._parse_task_response(response, target_difficulty)

        self.task_history.append(task)
        logger.info(f"Generated task {task.task_id}: {task.query[:100]}...")

        return task

    def _calculate_target_difficulty(self, performance: Optional[Dict]) -> str:
        """Calculate target difficulty based on executor performance."""
        if not performance or self.iteration <= 2:
            return 'easy'

        success_rate = performance.get('success_rate', 0.5)
        uncertainty = performance.get('uncertainty', 0.5)

        # Target tasks where executor has ~50% uncertainty (optimal learning zone)
        if uncertainty > 0.7 or success_rate < 0.3:
            return 'easier'  # Too hard, step back
        elif uncertainty < 0.3 and success_rate > 0.7:
            return 'harder'  # Too easy, increase difficulty
        else:
            return 'maintain'  # In optimal zone

    def _create_task_generation_prompt(self, difficulty: str, performance: Optional[Dict]) -> str:
        """Create prompt for task generation."""
        base_prompt = f"""
        Generate a research task with difficulty level: {difficulty}
        Iteration: {self.iteration}
        """

        if performance:
            base_prompt += f"""
        Executor Performance:
        - Success Rate: {performance.get('success_rate', 'N/A')}
        - Avg Uncertainty: {performance.get('uncertainty', 'N/A')}
        - Tool Usage: {performance.get('tool_usage', 'N/A')}

        Adjust complexity to maintain ~50% uncertainty.
        """

        base_prompt += """
        Generate a research query that:
        1. Requires multiple information sources
        2. Involves analysis and synthesis
        3. Has verifiable answers/insights

        Format your response as JSON:
        {
            "query": "The research question",
            "complexity": 0.0-1.0,
            "tool_requirements": ["web_search", "analysis", etc],
            "expected_reasoning_steps": ["step1", "step2", ...]
        }
        """

        return base_prompt

    def _parse_task_response(self, response: str, difficulty: str) -> ResearchTask:
        """Parse agent response into ResearchTask."""
        try:
            # Extract JSON from response
            import re
            json_match = re.search(r'\{.*\}', response, re.DOTALL)
            if json_match:
                task_data = json.loads(json_match.group())
            else:
                # Fallback to simple parsing
                task_data = {
                    "query": response.strip(),
                    "complexity": 0.5,
                    "tool_requirements": ["web_search"],
                    "expected_reasoning_steps": []
                }
        except Exception as e:
            logger.warning(f"Failed to parse task JSON: {e}")
            task_data = {
                "query": response.strip(),
                "complexity": 0.5,
                "tool_requirements": ["web_search"],
                "expected_reasoning_steps": []
            }

        return ResearchTask(
            task_id=f"task_{self.iteration}_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            query=task_data.get("query", response.strip()),
            complexity=float(task_data.get("complexity", 0.5)),
            difficulty=difficulty,
            tool_requirements=task_data.get("tool_requirements", ["web_search"]),
            generated_at=datetime.now()
        )

    def compute_curriculum_reward(self, task: ResearchTask, executor_responses: List[ExecutorResponse]) -> float:
        """
        Compute reward for curriculum agent based on executor responses.
        Implements Rc = Runc + Rtool - Rrep from the paper.
        """
        if not executor_responses:
            return 0.0

        # Uncertainty reward (maximize when uncertainty ~0.5)
        confidences = [r.confidence for r in executor_responses]
        avg_confidence = np.mean(confidences)
        uncertainty = 1 - avg_confidence
        r_unc = 1 - 2 * abs(uncertainty - 0.5)

        # Tool use reward
        tool_counts = [len(r.tool_calls) for r in executor_responses]
        avg_tools = np.mean(tool_counts)
        r_tool = min(avg_tools / 5.0, 1.0)  # Normalize to [0, 1]

        # Repetition penalty (penalize similar tasks)
        r_rep = self._compute_repetition_penalty(task)

        # Composite reward
        reward = 0.4 * r_unc + 0.4 * r_tool - 0.2 * r_rep

        logger.debug(f"Curriculum reward: Runc={r_unc:.2f}, Rtool={r_tool:.2f}, Rrep={r_rep:.2f}, Total={reward:.2f}")

        return reward

    def _compute_repetition_penalty(self, task: ResearchTask) -> float:
        """Compute penalty for repetitive tasks."""
        if len(self.task_history) < 2:
            return 0.0

        # Simple similarity check based on query overlap
        recent_tasks = self.task_history[-10:]  # Check last 10 tasks

        similarities = []
        for prev_task in recent_tasks:
            if prev_task.task_id == task.task_id:
                continue

            # Calculate word overlap
            words1 = set(task.query.lower().split())
            words2 = set(prev_task.query.lower().split())

            if len(words1) == 0 or len(words2) == 0:
                continue

            overlap = len(words1.intersection(words2))
            similarity = overlap / max(len(words1), len(words2))
            similarities.append(similarity)

        if similarities:
            return np.mean(similarities)
        return 0.0


class ExecutorAgent:
    """
    Executes research tasks with improving capabilities.
    Implements the executor evolution component of Agent0.
    """

    def __init__(self, session_db: SqliteDb, config: Dict[str, Any],
                 vector_store: VectorStore, file_manager: FileManager):
        """Initialize the executor agent."""
        self.session_db = session_db
        self.config = config
        self.vector_store = vector_store
        self.file_manager = file_manager
        self.iteration = 0
        self.performance_history: List[Dict] = []

        # Initialize Agno agent for task execution
        self.agent = Agent(
            model=OpenAIChat(
                id=config.get('model', 'gpt-4'),
                api_key=config.get('api_key')
            ),
            session=session_db,
            description="Executor Agent - Performs research tasks",
            instructions=self._get_executor_instructions(),
            tools=[ParallelDuckDuckGoSearch()]
        )

        # Initialize refinement components
        self.refiner = RefinementEngine(config)
        self.evaluator = ResearchEvaluator(config)

        logger.info("ExecutorAgent initialized")

    def _get_executor_instructions(self) -> str:
        """Get the system instructions for the executor agent."""
        return """
        You are an Executor Agent responsible for completing research tasks.

        Your objectives:
        1. Complete research tasks accurately and thoroughly
        2. Use available tools effectively (web search, analysis)
        3. Provide comprehensive, well-sourced responses
        4. Show clear reasoning steps
        5. Express confidence levels appropriately

        Research Process:
        1. Understand the task requirements
        2. Plan your approach
        3. Gather information from multiple sources
        4. Analyze and synthesize findings
        5. Present conclusions with evidence

        Always cite sources and explain your reasoning process.
        """

    async def execute_task(self, task: ResearchTask, num_attempts: int = 3) -> List[ExecutorResponse]:
        """
        Execute a research task with multiple attempts for self-consistency.

        Args:
            task: The research task to execute
            num_attempts: Number of execution attempts for self-consistency

        Returns:
            List of ExecutorResponse objects
        """
        self.iteration += 1
        responses = []

        for attempt in range(num_attempts):
            logger.info(f"Executing task {task.task_id}, attempt {attempt + 1}/{num_attempts}")

            # Execute task
            start_time = datetime.now()
            response = await self._execute_single_attempt(task)
            execution_time = (datetime.now() - start_time).total_seconds()

            # Create ExecutorResponse
            executor_response = ExecutorResponse(
                task_id=task.task_id,
                response=response['content'],
                sources=response.get('sources', []),
                tool_calls=response.get('tool_calls', []),
                confidence=response.get('confidence', 0.5),
                success=response.get('success', False),
                reasoning_steps=response.get('reasoning_steps', []),
                execution_time=execution_time
            )

            responses.append(executor_response)

        # Update performance metrics
        self._update_performance(task, responses)

        return responses

    async def _execute_single_attempt(self, task: ResearchTask) -> Dict:
        """Execute a single attempt at a research task."""
        prompt = f"""
        Research Task: {task.query}

        Requirements:
        - Use web search to gather information
        - Provide comprehensive analysis
        - Cite all sources
        - Show reasoning steps
        - Express confidence (0.0-1.0) in your findings

        Format your response with:
        1. Research findings
        2. Analysis and synthesis
        3. Sources used
        4. Confidence level
        5. Reasoning steps taken
        """

        try:
            # Execute through agent
            result = self.agent.run(prompt)

            # Parse and structure response
            structured_response = self._parse_executor_response(result)

            # Store in vector database for future reference
            await self._store_research_results(task, structured_response)

            return structured_response

        except Exception as e:
            logger.error(f"Execution failed: {e}")
            return {
                'content': f"Error executing task: {str(e)}",
                'sources': [],
                'tool_calls': [],
                'confidence': 0.0,
                'success': False,
                'reasoning_steps': []
            }

    def _parse_executor_response(self, response: str) -> Dict:
        """Parse executor response into structured format."""
        # Extract different components from response
        # This is a simplified parser - in production, use more robust parsing

        import re

        # Extract confidence
        confidence_match = re.search(r'confidence[:\s]+([0-9.]+)', response.lower())
        confidence = float(confidence_match.group(1)) if confidence_match else 0.5

        # Extract sources (simple URL extraction)
        url_pattern = r'https?://[^\s)]+'
        sources = re.findall(url_pattern, response)

        # Detect tool usage
        tool_calls = []
        if 'search' in response.lower():
            tool_calls.append('web_search')
        if 'analyz' in response.lower():
            tool_calls.append('analysis')

        # Extract reasoning steps (look for numbered lists)
        steps_pattern = r'\d+\.\s+([^\n]+)'
        reasoning_steps = re.findall(steps_pattern, response)

        return {
            'content': response,
            'sources': [{'url': url} for url in sources],
            'tool_calls': tool_calls,
            'confidence': confidence,
            'success': confidence > 0.6,
            'reasoning_steps': reasoning_steps
        }

    async def _store_research_results(self, task: ResearchTask, response: Dict):
        """Store research results in vector database."""
        try:
            # Create document for vector store
            doc = {
                'content': response['content'],
                'metadata': {
                    'task_id': task.task_id,
                    'query': task.query,
                    'timestamp': datetime.now().isoformat(),
                    'confidence': response['confidence'],
                    'sources': response['sources']
                }
            }

            # Store in vector database
            self.vector_store.add_texts(
                texts=[doc['content']],
                metadatas=[doc['metadata']]
            )

            logger.debug(f"Stored research results for task {task.task_id}")

        except Exception as e:
            logger.error(f"Failed to store results: {e}")

    def _update_performance(self, task: ResearchTask, responses: List[ExecutorResponse]):
        """Update executor performance metrics."""
        if not responses:
            return

        # Calculate metrics
        confidences = [r.confidence for r in responses]
        successes = [r.success for r in responses]
        tool_counts = [len(r.tool_calls) for r in responses]

        performance = {
            'iteration': self.iteration,
            'task_id': task.task_id,
            'success_rate': np.mean(successes),
            'uncertainty': 1 - np.mean(confidences),
            'consistency': 1 - np.std(confidences),  # How consistent are confidence levels
            'tool_usage': np.mean(tool_counts),
            'avg_execution_time': np.mean([r.execution_time for r in responses])
        }

        self.performance_history.append(performance)
        logger.info(f"Performance update: Success={performance['success_rate']:.2f}, "
                   f"Uncertainty={performance['uncertainty']:.2f}")

    def get_performance_summary(self) -> Dict:
        """Get summary of executor performance."""
        if not self.performance_history:
            return {}

        recent = self.performance_history[-10:]  # Last 10 tasks

        return {
            'success_rate': np.mean([p['success_rate'] for p in recent]),
            'uncertainty': np.mean([p['uncertainty'] for p in recent]),
            'consistency': np.mean([p['consistency'] for p in recent]),
            'tool_usage': np.mean([p['tool_usage'] for p in recent]),
            'iterations_completed': self.iteration
        }


class Agent0ResearchSession:
    """
    Main orchestrator for Agent0 self-evolving research system.
    Implements the co-evolutionary loop between curriculum and executor agents.
    """

    def __init__(self, config: Dict[str, Any], file_manager: FileManager,
                 vector_store: VectorStore):
        """Initialize Agent0 research session."""
        self.config = config
        self.file_manager = file_manager
        self.vector_store = vector_store
        self.iteration = 0
        self.max_iterations = config.get('max_iterations', 10)

        # Initialize database
        self.session_db = SqliteDb(
            db_path=Path(config.get('db_path', './agent0_session.db')),
            user_id='agent0_user'
        )

        # Initialize agents
        self.curriculum_agent = CurriculumAgent(self.session_db, config)
        self.executor_agent = ExecutorAgent(
            self.session_db, config, vector_store, file_manager
        )

        # Track co-evolution progress
        self.evolution_history = []

        logger.info("Agent0 Research Session initialized")

    async def run_session(self, initial_topic: str) -> Dict[str, Any]:
        """
        Run the Agent0 co-evolutionary research session.

        Args:
            initial_topic: Initial research topic to bootstrap the system

        Returns:
            Session results and insights
        """
        logger.banner([
            "Agent0 Self-Evolving Research",
            f"Topic: {initial_topic}",
            f"Max Iterations: {self.max_iterations}"
        ])

        # Bootstrap with initial topic
        await self._bootstrap_session(initial_topic)

        # Main co-evolutionary loop
        for iteration in range(self.max_iterations):
            self.iteration = iteration + 1
            logger.section(f"Co-Evolution Iteration {self.iteration}")

            # Phase 1: Curriculum Evolution
            logger.info("Phase 1: Curriculum Generation")
            executor_performance = self.executor_agent.get_performance_summary()
            task = self.curriculum_agent.generate_task(executor_performance)

            # Phase 2: Executor Evolution
            logger.info("Phase 2: Task Execution")
            responses = await self.executor_agent.execute_task(task)

            # Compute rewards and update agents
            curriculum_reward = self.curriculum_agent.compute_curriculum_reward(task, responses)

            # Track evolution progress
            self._track_evolution(task, responses, curriculum_reward)

            # Check for convergence or early stopping
            if self._should_stop():
                logger.info("Convergence detected or stopping criteria met")
                break

            # User interaction point (optional)
            if iteration % 3 == 0:  # Every 3 iterations
                should_continue = await self._user_checkpoint(task, responses)
                if not should_continue:
                    break

        # Generate final report
        report = await self._generate_final_report()

        logger.success("Agent0 Research Session completed")
        return report

    async def _bootstrap_session(self, topic: str):
        """Bootstrap the session with an initial topic."""
        logger.info(f"Bootstrapping with topic: {topic}")

        # Create initial simple task
        bootstrap_task = ResearchTask(
            task_id="bootstrap",
            query=f"What are the key aspects and recent developments in: {topic}",
            complexity=0.3,
            difficulty="easy",
            tool_requirements=["web_search"],
            generated_at=datetime.now()
        )

        # Execute bootstrap task to seed the system
        responses = await self.executor_agent.execute_task(bootstrap_task, num_attempts=1)
        logger.info("Bootstrap phase completed")

    def _track_evolution(self, task: ResearchTask, responses: List[ExecutorResponse],
                        curriculum_reward: float):
        """Track co-evolution progress."""
        evolution_step = {
            'iteration': self.iteration,
            'task': {
                'query': task.query,
                'complexity': task.complexity,
                'difficulty': task.difficulty
            },
            'executor_performance': {
                'num_responses': len(responses),
                'avg_confidence': np.mean([r.confidence for r in responses]),
                'success_rate': np.mean([r.success for r in responses]),
                'avg_tool_calls': np.mean([len(r.tool_calls) for r in responses])
            },
            'curriculum_reward': curriculum_reward,
            'timestamp': datetime.now().isoformat()
        }

        self.evolution_history.append(evolution_step)

        # Log progress
        logger.metric("Evolution Progress", {
            'Iteration': self.iteration,
            'Task Complexity': f"{task.complexity:.2f}",
            'Executor Confidence': f"{evolution_step['executor_performance']['avg_confidence']:.2f}",
            'Curriculum Reward': f"{curriculum_reward:.2f}"
        })

    def _should_stop(self) -> bool:
        """Check if co-evolution should stop."""
        if len(self.evolution_history) < 3:
            return False

        # Check for convergence (stable performance over last 3 iterations)
        recent = self.evolution_history[-3:]
        complexities = [e['task']['complexity'] for e in recent]
        confidences = [e['executor_performance']['avg_confidence'] for e in recent]

        # If complexity and confidence are stable, consider converged
        complexity_stable = np.std(complexities) < 0.1
        confidence_stable = np.std(confidences) < 0.1

        return complexity_stable and confidence_stable

    async def _user_checkpoint(self, task: ResearchTask, responses: List[ExecutorResponse]) -> bool:
        """Interactive checkpoint with the user."""
        print("\n" + "="*60)
        print("AGENT0 CHECKPOINT")
        print("="*60)
        print(f"\nIteration {self.iteration} Summary:")
        print(f"Current Task: {task.query[:100]}...")
        print(f"Task Complexity: {task.complexity:.2f}")
        print(f"Executor Confidence: {np.mean([r.confidence for r in responses]):.2f}")

        # Show sample response
        if responses:
            print("\nSample Executor Response (truncated):")
            print(responses[0].response[:500] + "...")

        print("\n[C]ontinue | [S]top | [M]odify parameters | [V]iew full progress")

        choice = input("\nYour choice: ").strip().lower()

        if choice == 's':
            return False
        elif choice == 'v':
            self._display_progress()
            return await self._user_checkpoint(task, responses)  # Re-show menu
        elif choice == 'm':
            # Allow parameter modification
            print("\nParameter modification not yet implemented")

        return True  # Continue by default

    def _display_progress(self):
        """Display co-evolution progress."""
        print("\n" + "="*60)
        print("CO-EVOLUTION PROGRESS")
        print("="*60)

        for i, step in enumerate(self.evolution_history, 1):
            print(f"\nIteration {i}:")
            print(f"  Task: {step['task']['query'][:80]}...")
            print(f"  Complexity: {step['task']['complexity']:.2f}")
            print(f"  Confidence: {step['executor_performance']['avg_confidence']:.2f}")
            print(f"  Success Rate: {step['executor_performance']['success_rate']:.2f}")
            print(f"  Tool Calls: {step['executor_performance']['avg_tool_calls']:.1f}")
            print(f"  Curriculum Reward: {step['curriculum_reward']:.2f}")

    async def _generate_final_report(self) -> Dict[str, Any]:
        """Generate comprehensive final report."""
        logger.info("Generating final research report...")

        # Collect all executor responses
        all_responses = []
        for step in self.evolution_history:
            # In practice, we'd store and retrieve actual responses
            pass

        # Calculate overall metrics
        final_complexity = self.evolution_history[-1]['task']['complexity'] if self.evolution_history else 0
        avg_confidence = np.mean([s['executor_performance']['avg_confidence'] for s in self.evolution_history])

        report = {
            'session_summary': {
                'total_iterations': self.iteration,
                'final_task_complexity': final_complexity,
                'average_executor_confidence': avg_confidence,
                'convergence_achieved': self._should_stop()
            },
            'evolution_trajectory': [
                {
                    'iteration': s['iteration'],
                    'complexity': s['task']['complexity'],
                    'confidence': s['executor_performance']['avg_confidence'],
                    'reward': s['curriculum_reward']
                }
                for s in self.evolution_history
            ],
            'key_insights': self._extract_key_insights(),
            'research_outputs': await self._compile_research_outputs(),
            'timestamp': datetime.now().isoformat()
        }

        # Save report
        report_path = self.file_manager.get_session_path() / "agent0_report.json"
        with open(report_path, 'w') as f:
            json.dump(report, f, indent=2)

        logger.success(f"Report saved to: {report_path}")

        return report

    def _extract_key_insights(self) -> List[str]:
        """Extract key insights from the research process."""
        insights = []

        if self.evolution_history:
            # Complexity progression
            initial_complexity = self.evolution_history[0]['task']['complexity']
            final_complexity = self.evolution_history[-1]['task']['complexity']
            insights.append(f"Task complexity evolved from {initial_complexity:.2f} to {final_complexity:.2f}")

            # Performance improvement
            initial_confidence = self.evolution_history[0]['executor_performance']['avg_confidence']
            final_confidence = self.evolution_history[-1]['executor_performance']['avg_confidence']
            insights.append(f"Executor confidence improved from {initial_confidence:.2f} to {final_confidence:.2f}")

            # Tool usage evolution
            avg_tools = np.mean([s['executor_performance']['avg_tool_calls'] for s in self.evolution_history])
            insights.append(f"Average tool usage: {avg_tools:.1f} calls per task")

        return insights

    async def _compile_research_outputs(self) -> Dict:
        """Compile all research outputs."""
        # This would aggregate all the research findings from vector store
        # For now, return a summary structure

        return {
            'total_sources_analyzed': len(self.evolution_history) * 3,  # Approximate
            'knowledge_base_size': self.vector_store.get_collection_size() if hasattr(self.vector_store, 'get_collection_size') else 0,
            'research_depth': 'Advanced' if self.iteration > 7 else 'Intermediate' if self.iteration > 3 else 'Basic'
        }


# Integration function for main orchestrator
async def start_agent0_session(config: Dict, file_manager: FileManager,
                              vector_store: VectorStore, initial_topic: str) -> Dict:
    """
    Start an Agent0 self-evolving research session.

    This function integrates with the existing research orchestrator.
    """
    session = Agent0ResearchSession(config, file_manager, vector_store)
    results = await session.run_session(initial_topic)
    return results